version: '3'

tasks:
  run:
    cmds:
      - go run ./cmd/sso/ --config=./config/local.yaml 
  migrate:
    cmds:
      - go run ./cmd/migrator/ --storage-path=./storage/sqlite/sso.db --migrations-path=./migrations/sqlite
  migrate_test:
    cmds:
      - go run ./cmd/migrator/ --storage-path=./storage/sqlite/sso.db --migrations-path=./tests/migrations --migrations-table=migrations_test